//
//  SchoolSymbols.swift
//  AbsenceTracker
//
//  Created by Paulina Lopez Holguin on 03/04/24.
//

import Foundation

let schoolSymbols = [
    "book",
    "graduationcap",
    "pencil",
    "square.and.pencil",
    "lightbulb",
    "paperclip",
    "folder",
    "person.3",
    "person.fill",
    "person.2",
    "person.2.fill",
    "person.3.fill",
    "highlighter",
    "scissors",
    "square.grid.3x3.fill.square",
    "rectangle.and.pencil.and.ellipsis",
    "scalemass",
    "pencil.and.outline",
    "scalemass.fill",
    "square.stack.3d.up.slash",
    "studentdesk",
    "table",
    "tram.fill",
    "car.fill",
    "tray.fill",
    "airplane",
    "airplane.fill",
    "paperplane",
    "paperplane.fill",
    "graduationcap.fill",
    "book.circle",
    "book.circle.fill",
    "book.fill",
    "book.fill.circle",
    "books.vertical",
    "books.vertical.fill",
    "person.3.fill",
    "person.crop.circle",
    "person.crop.circle.badge.checkmark",
    "person.crop.circle.badge.xmark",
    "person.crop.circle.badge.exclamationmark",
    "person.crop.circle.badge.plus",
    "person.crop.circle.badge.minus",
    "person.crop.circle.badge.questionmark",
    "person.crop.circle.badge.checkmark.fill",
    "person.crop.circle.badge.xmark.fill",
    "person.crop.circle.badge.exclamationmark.fill",
    "person.crop.circle.badge.plus.fill",
    "person.crop.circle.badge.minus.fill",
    "person.crop.circle.badge.questionmark.fill",
    "person.2.square.stack",
    "person.3.sequence",
    "person.2.circle",
    "person.2.circle.fill",
    "person.2.fill",
    "person.3.fill",
    "person.3.sequence.fill",
    "person.crop.circle.fill.badge.checkmark",
    "person.crop.circle.fill.badge.xmark",
    "person.crop.circle.fill.badge.exclamationmark",
    "person.crop.circle.fill.badge.plus",
    "person.crop.circle.fill.badge.minus",
    "person.crop.circle.fill.badge.questionmark",
    "graduationcap",
    "graduationcap.fill"
]
